services:
  app:
    build: .
    container_name: fastapi01
    command: uvicorn app.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine